<?php
include './header.php';
?>

<dv>
    <select></select>
    <br>
    <br>

    <table border="1">
        <tr>
            <th>Schedule</th>
            <th>5am</th>
            <th>6am</th>
            <th>7am</th>
            <th>8am</th>
            <th>9am</th>
            <th>10am</th>
            <th>11am</th>
            <th>12md</th>
            <th>1pm</th>
            <th>2pm</th>
            <th>3pm</th>
            <th>4pm</th>
            <th>5pm</th>
            <th>6pm</th>
            <th>7pm</th>
            <th>8pm</th>
            <th>9pm</th>
            <th>10pm</th>
        </tr>
        <tr>
            <th>Monday</th>
            <td>0,0</td>
            <td>0,1</td>
            <td>0,2</td>
            <td>0,3</td>
            <td>0,4</td>
            <td>0,5</td>
            <td>0,6</td>
            <td>0,7</td>
            <td>0,8</td>
            <td>0,9</td>
            <td>0,10</td>
            <td>0,11</td>
            <td>0,12</td>
            <td>0,13</td>
            <td>0,14</td>
            <td>0,15</td>
            <td>0,16</td>
            <td>0,17</td>
        </tr>
        <tr>
            <th>Tuesday</th>
            <td>1,0</td>
            <td>1,1</td>
            <td>1,2</td>
            <td>1,3</td>
            <td>1,4</td>
            <td>1,5</td>
            <td>1,6</td>
            <td>1,7</td>
            <td>1,8</td>
            <td>1,9</td>
            <td>1,10</td>
            <td>1,11</td>
            <td>1,12</td>
            <td>1,13</td>
            <td>1,14</td>
            <td>1,15</td>
            <td>1,16</td>
            <td>1,17</td>
        </tr>
        <tr>
            <th>Wednesday</th>
            <td>2,0</td>
            <td>2,1</td>
            <td>2,2</td>
            <td>2,3</td>
            <td>2,4</td>
            <td>2,5</td>
            <td>2,6</td>
            <td>2,7</td>
            <td>2,8</td>
            <td>2,9</td>
            <td>2,10</td>
            <td>2,11</td>
            <td>2,12</td>
            <td>2,13</td>
            <td>2,14</td>
            <td>2,15</td>
            <td>2,16</td>
            <td>2,17</td>
        </tr>
        <tr>
            <th>Thursday</th>
            <td>3,0</td>
            <td>3,1</td>
            <td>3,2</td>
            <td>3,3</td>
            <td>3,4</td>
            <td>3,5</td>
            <td>3,6</td>
            <td>3,7</td>
            <td>3,8</td>
            <td>3,9</td>
            <td>3,10</td>
            <td>3,11</td>
            <td>3,12</td>
            <td>3,13</td>
            <td>3,14</td>
            <td>3,15</td>
            <td>3,16</td>
            <td>3,17</td>
        </tr>
        <tr>
            <th>Friday</th>
            <td>4,0</td>
            <td>4,1</td>
            <td>4,2</td>
            <td>4,3</td>
            <td>4,4</td>
            <td>4,5</td>
            <td>4,6</td>
            <td>4,7</td>
            <td>4,8</td>
            <td>4,9</td>
            <td>4,10</td>
            <td>4,11</td>
            <td>4,12</td>
            <td>4,13</td>
            <td>4,14</td>
            <td>4,15</td>
            <td>4,16</td>
            <td>4,17</td>
        </tr>

    </table>

</dv>
